---
title: "My interactive Rmd!"
author: "Roshni Katrak-Adefowora"
date: "1/31/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

```{r flippers, echo = FALSE}

inputPanel(
  
  selectInput(inputId = "pick_spp",
              label = "Pick your penguin species:",
              choices = c("Adélie" = "Adelie", "Cool Chinstrap" = "Chinstrap", "Gentoo"), selected = "Gentoo"),
  
  sliderInput(inputId = "pt_size", 
              label = "Set your point size:",
              min = 1, 
              max = 10,
              step = 0.5, #increments
              value = 5) #starting value
  
)

############## Create reactive subset of penguins data based on user selection for species

penguin_set <- reactive({
  penguins %>% 
    filter(species == input$pick_spp)
})

# create reactive plot

renderPlot({
  
  ggplot(data = penguin_set(), aes(x = flipper_length_mm, y = body_mass_g))+
    geom_point(size = input$pt_size)
  
})
```

